---
version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - npm i
    build:
        commands:
            - echo 'Building'
            - npm run build
artifacts:
    files:
        - ./**/*
    base-directory: 'dist'
