---
version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - npm i
    build:
        commands:
            - echo 'Building'
            - npm run generate
artifacts:
    files:
        - ./**/*
    base-directory: 'public'
