name: Deploy by Codepipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Trigger AWS CodePipeline
              # v1.0.7
              uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
              with:
                  aws-region: 'ap-northeast-1'
                  aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
                  aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
                  pipeline-name: 'blog-s3-deploy'
